# Generated by Django 4.2 on 2023-04-29 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_mensajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='texto',
            field=models.TextField(verbose_name='Mensaje'),
        ),
    ]
