# Generated by Django 4.2 on 2023-04-29 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mensajes', '0002_conversacion_creador_alter_mensaje_texto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversacion',
            name='creador',
        ),
    ]
