# Generated by Django 4.2 on 2023-04-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mensajes', '0003_remove_conversacion_creador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversacion',
            options={'verbose_name_plural': 'Conversaciones'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'verbose_name_plural': 'Mensajes'},
        ),
    ]
