# Generated by Django 4.2 on 2023-05-22 23:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mensajes', '0004_alter_conversacion_options_alter_mensaje_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='texto',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
