# Generated by Django 4.2 on 2023-05-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mensajes', '0005_alter_mensaje_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='texto',
            new_name='mensaje',
        ),
    ]
