# Generated by Django 4.2 on 2023-04-28 15:09

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('tipologia', models.CharField(max_length=30)),
                ('superficie', models.FloatField()),
                ('plantas', models.IntegerField()),
                ('dormitorios', models.IntegerField()),
                ('banios', models.IntegerField(verbose_name='baños')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas')),
                ('memoria_descriptiva', ckeditor.fields.RichTextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
