# Generated by Django 4.2 on 2023-04-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='planos',
            field=models.FileField(blank=True, null=True, upload_to='planos/'),
        ),
    ]
