# Generated by Django 4.2 on 2023-04-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyectos', '0003_alter_proyecto_planos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name_plural': 'Proyectos'},
        ),
    ]
