# Generated by Django 4.2 on 2023-05-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0002_alter_infoadicional_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoadicional',
            name='pronombres',
            field=models.CharField(blank=True, choices=[('he', 'Él'), ('she', 'Ella'), ('they', 'Elle'), ('other', 'Otros')], max_length=10, null=True),
        ),
    ]
