# Generated by Django 4.2 on 2023-05-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0003_infoadicional_pronombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoadicional',
            name='pronombres',
            field=models.CharField(blank=True, choices=[('he', 'Él'), ('she', 'Ella'), ('they', 'Elle'), ('other', 'Otros')], default='other', max_length=10, null=True),
        ),
    ]
